# Generated by Django 3.0.5 on 2020-05-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=20)),
                ('course', models.CharField(choices=[('1', 'first'), ('2', 'second'), ('3', 'third'), ('4', 'forth'), ('1m', 'first master'), ('2m', 'second master')], max_length=2)),
            ],
        ),
    ]
