# Generated by Django 3.0.5 on 2020-05-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoryApp', '0004_remove_checkinentry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinentry',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
