# Generated by Django 3.0.5 on 2020-05-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoryApp', '0005_checkinentry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rententry',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='rententry',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='rententry',
            name='telephone',
            field=models.CharField(default=None, max_length=13),
        ),
    ]
