# Generated by Django 3.0.5 on 2020-05-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoryApp', '0006_auto_20200505_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesentry',
            name='rule',
            field=models.TextField(),
        ),
    ]
