# Generated by Django 3.0.5 on 2020-05-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoryApp', '0009_remove_workentry_max_exec'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_clocks',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='your_clocks',
            field=models.PositiveIntegerField(default=40),
            preserve_default=False,
        ),
    ]
