# Generated by Django 3.0.5 on 2020-05-07 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoryApp', '0010_auto_20200507_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workentry',
            name='executer',
        ),
        migrations.AddField(
            model_name='workentry',
            name='exec_men',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_clocks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='your_clocks',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
