# Generated by Django 3.0.5 on 2020-05-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoryApp', '0011_auto_20200508_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
