# Generated by Django 3.0.5 on 2020-05-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoryApp', '0012_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
